### ISSUE TITLE
ModuleNotFoundError: No module named 'pyspatialml.temporary_files'

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [stevenpawley/Pyspatialml#34]
Got this issue when running on Colab

/usr/local/lib/python3.7/dist-packages/pyspatialml/preprocessing.py in <module>()
      6 
      7 from .raster import Raster
----> 8 from .temporary_files import _file_path_tempfile
      9 
     10 
ModuleNotFoundError: No module named 'pyspatialml.temporary_files'

**Comment by stevenpawley** [comment]
Hello,

Maybe try using the version from GitHub because some changes have been made since I last updated pypi; I think that this probably is already resolved. I'm looking to push a new version to pypi over the next few days as well.

**Comment by Daniel-Trung-Nguyen** [comment]
Hi Steven,
Just ran it today from Google Colab. The error still persists in the Pypi version
Cheers,
Daniel

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-f2f5c1ab7861> in <module>()
      5 import numpy as np
      6 from pyspatialml import Raster
----> 7 from pyspatialml.preprocessing import xy_coordinates, distance_to_corners, distance_to_samples
      8 import pyspatialml.datasets.meuse as ms
      9 

/usr/local/lib/python3.7/dist-packages/pyspatialml/preprocessing.py in <module>()
      6 
      7 from .raster import Raster
----> 8 from .temporary_files import _file_path_tempfile
